name: firebasetest
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.1.0
  firebase_database: ^6.1.2
  flutter_animation_progress_bar: ^2.0.0
  wave_progress_widget: ^0.0.1
  waveprogressbar_flutter: ^0.1.2
  provider: ^5.0.0
  flutter_spinkit: ^5.0.0
  flutter_local_notifications: ^5.0.0+3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  
